import { Chat } from "../chat";

export const listeChats: Chat[] = [
    {
        nom: "arobase",
        sexe: "m",
        robe: "Red Silver Tabby",
        statut: "reserve",
        anniv: "15/05/2023",
        poids: [1661,"g",2,"mo"],
        pere: "uragon",
        mere: "udaipur",
        cattery: "coon castle",
        tests: "en cours",
        tarif: 1900,
        photos: [
            "arobase-18.jpg",
            "arobase-17.jpg",
            "arobase-16.jpg",
            "arobase-15.jpg",
            "arobase-14.png",
            "arobase-13.png",
            "asterix-1.jpg",
            "asterix-2.jpg",
            "asterix-3.jpg",
            "asterix-4.jpg",
            "asterix-5.jpg",
            "asterix-6.jpg",
            "asterix-7.jpg",
            "asterix-8.jpg",
            "asterix-9.jpg",
            "asterix-10.jpg",
            "asterix-11.jpg",
            "asterix-12.jpg",
        ],
        blabla: "Arobase a déjà une âme de leader."
    },
    {
        nom: "atome",
        sexe: "m",
        robe: "Brown Tabby",
        statut: "reserve",
        anniv: "15/05/2023",
        poids: [1686,"g",2,"mo"],
        pere: "uragon",
        mere: "udaipur",
        cattery: "coon castle",
        tests: "en cours",
        tarif: 1800,
        photos: [
            "atome-23.jpg",
            "atome-22.jpg",
            "atome-21.jpg",
            "atome-20.jpg",
            "atome-19.jpg",
            "atome-18.jpg",
            "atome-17.jpg",
            "atome-16.jpg",
            "atome-15.jpg",
            "atome-14.jpg",
            "atome-13.jpg",
            "atome-12.jpg",
            "atome-11.jpg",
            "atome-10.jpg",
            "atome-9.jpg",
            "atome-8.jpg",
            "atome-7.jpg",
            "atome-6.jpg",
            "atome-5.jpg",
            "atome-4.jpg",
            "atome-3.jpg",
            "atome-2.jpg",
            "atome-1.jpg",
        ],
        blabla: "Atome est le mâle le plus costaud de la portée et a un appétit débordant."
    },
    {
        nom: "azote",
        sexe: "f",
        robe: "Black Silver Tabby",
        statut: "eval",
        anniv: "15/05/2023",
        poids: [1407,"g",2,"mo"],
        pere: "uragon",
        mere: "udaipur",
        cattery: "coon castle",
        tests: "en cours",
        tarif: 1500,
        photos: [
            "azote-13.jpg",
            "azote-12.jpg",
            "azote-11.jpg",
            "azote-10.jpg",
            "azote-9.jpg",
            "azote-8.jpg",
            "azote-7.jpg",
            "azote-6.jpg",
            "azote-5.jpg",
            "azote-4.jpg",
            "azote-3.jpg",
            "azote-2b.png",
            "astuce-2.jpg",
            "astuce-1.jpg",
        ]
    },
    {
        nom: "artémis",
        sexe: "f",
        robe: "Black Silver Tabby",
        statut: "reserve",
        anniv: "15/05/2023",
        poids: [1343,"g",2,"mo"],
        pere: "uragon",
        mere: "udaipur",
        cattery: "coon castle",
        tests: "en cours",
        tarif: 1500,
        photos: [
            "artémis-20.jpg",
            "artémis-19.jpg",
            "artémis-18.jpg",
            "artémis-17.jpg",
            "artémis-16.jpg",
            "artémis-15.jpg",
            "artémis-14.jpg",
            "artémis-13.jpg",
            "artémis-12.png",
            "artémis-11.jpg",
            "artémis-10.jpg",
            "artémis-1.jpg",
            "artémis-2.jpg",
            "artémis-3.jpg",
            "artémis-4.jpg",
            "artémis-5.jpg",
            "artémis-6.jpg",
            "artémis-7.jpg",
            "artémis-8.jpg",
            "artémis-9.jpg",
        ]
    },
    {
        nom: "abi",
        sexe: "f",
        robe: "Black Silver Tabby",
        statut: "reserve",
        anniv: "15/05/2023",
        poids: [1223,"g",2,"mo"],
        pere: "uragon",
        mere: "udaipur",
        cattery: "coon castle",
        tests: "en cours",
        tarif: 1500,
        photos: [
            "achille-15.jpg",
            "achille-14.jpg",
            "achille-13.jpg",
            "achille-12.jpg",
            "achille-11.jpg",
            "achille-10.jpg",
            "achille-9.jpg",
            "achille-8b.png",
            "achille-8.jpg",
            "achille-7.jpg",
            "achille-1.jpg",
            "achille-2.jpg",
            "achille-2b.jpg",
            "achille-3.jpg",
            "achille-4.jpg",
            "achille-5.jpg",
            "achille-6.jpg",
        ],
        blabla: "Pesant 66 grammes à la naissance, Achille a survécu et mérite son prénom de combattant."
    },
    {
        nom: "udaipur",
        sexe: "f",
        robe: "Brown Blotched Tortie Tabby",
        statut: "adulte",
        anniv: "26/07/2023",
        poids: [6.5,"k",22,"mo"],
        pere: "thorghal",
        mere: "sekhmet",
        cattery: "mourre-frais",
        tests: "HCM N/N, PKDEF N/N, SMA N/N",
        concours: "2 points CAC LOOF, en route vers le titre de Championne",
        loof: "LOOF 2023 2542",
        blabla: "bon chacha",
        photos: [
            "uzi-1.jpeg",
            "uzi-2.jpeg",
            "uzi-3.jpeg",
            "uzi-4.jpeg",
            "uzi-5.jpeg",
            "uzi-6.jpeg",
            "uzi-7.jpeg",
            "uzi-8.jpeg",
            "uzi-9.jpeg"
        ],
    },
    {
        nom: "uragon",
        sexe: "m",
        robe: "Black silver blotched tabby",
        statut: "adulte",
        anniv: "02/04/2023",
        poids: [8,"k",2,"a"],
        cattery: "Wind of Coon",
        tests: "HCM N/N, PKDEF N/N, SMA N/N",
        concours: "Grand Champion d'Europe <br> Second chat de France en 2024 <br> Champion du Monde",
        blabla: "Tempérament équilibré. Uragon est à la fois joueur, curieux, doux et calme. Très proche de son frère Tyson, avec lequel il ne se dispute jamais. Il est papa pour la seconde fois en mai suite à son mariage avec Udaipur de Mourre-frais qui a eu lieu en mars. Fils du célèbre BigBoss, son pedigree est prestigieux.",
        photos: ["uragon-1.jpeg","uragon-2.jpeg", "uragon-3.jpeg", "uragon-4.jpeg","uragon-5.jpeg"],
        pere: "Big Boss",
        mere: "Cats Coon Reden"
    }
];