import { Chat } from "../chat";

export const listeChats: Chat[] = [
    {
        nom: "vigo",
        sexe: "m",
        robe: "Red silver",
        statut: "dispo",
        anniv: "15/05/2023",
        poids: [139,"g",0,"j"],
        pere: "uragon",
        mere: "udaipur",
        cattery: "coon castle",
        tests: "HCM N/N, PKDEF N/N, SMA N/N",
        tarif: 1200,
    },
    {
        nom: "vie",
        sexe: "f",
        robe: "Black silver",
        statut: "dispo",
        anniv: "15/05/2023",
        poids: [142,"g",0,"j"],
        pere: "uragon",
        mere: "udaipur",
        cattery: "coon castle",
        tests: "HCM N/N, PKDEF N/N, SMA N/N",
        tarif: 1500,
    },
    {
        nom: "vitalis",
        sexe: "m",
        robe: "Black silver",
        statut: "reserve",
        anniv: "15/05/2023",
        poids: [128,"g",0,"j"],
        pere: "uragon",
        mere: "udaipur",
        cattery: "coon castle",
        tests: "HCM N/N, PKDEF N/N, SMA N/N",
        tarif: 2500,
        adoptant: "Sophie"
    },
    {
        nom: "viagra",
        sexe: "m",
        robe: "Black silver",
        statut: "option",
        anniv: "15/05/2023",
        poids: [133,"g",0,"j"],
        pere: "uragon",
        mere: "udaipur",
        cattery: "coon castle",
        tests: "HCM N/N, PKDEF N/N, SMA N/N",
        tarif: 2200,
        adoptant: "Jean"
    },
    {
        nom: "volo",
        sexe: "m",
        robe: "Blue",
        statut: "eval",
        anniv: "15/05/2023",
        poids: [131,"g",0,"j"],
        pere: "uragon",
        mere: "udaipur",
        cattery: "coon castle",
        tests: "HCM N/N, PKDEF N/N, SMA N/N",
        tarif: 1900,
    },
    {
        nom: "valentine",
        sexe: "f",
        robe: "Brown blotched tabby",
        statut: "reserve",
        anniv: "15/05/2023",
        poids: [115,"g",0,"j"],
        pere: "uragon",
        mere: "udaipur",
        cattery: "coon castle",
        tests: "HCM N/N, PKDEF N/N, SMA N/N",
        tarif: 1800,
        adoptant: "Alexis"
    },
    {
        nom: "udaipur",
        sexe: "f",
        robe: "Brown tortie blotched tabby",
        statut: "adulte",
        anniv: "26/07/2023",
        poids: [6.5,"k",18,"mo"],
        pere: "thorghal",
        mere: "sekhmet",
        cattery: "mourre-frais",
        tests: "HCM N/N, PKDEF N/N, SMA N/N",
        concours: ["Championne LOOF"],
        loof: "LOOF 2023 2542",
        blabla: "bon chacha",
        photos: [
            "uzi-main.jpeg",
            "uzi-2.jpeg",
            "uzi-3.jpeg",
            "uzi-4.jpeg",
            "uzi-5.jpeg",
            "uzi-6.jpeg",
            "uzi-7.jpeg",
            "uzi-8.jpeg",
            "uzi-9.jpeg"
        ]
    },
    {
        nom: "uragon",
        sexe: "m",
        robe: "Black silver ticket tabby",
        statut: "adulte",
        anniv: "02/04/2023",
        poids: [8,"k",2,"a"],
        cattery: "wind of coon",
        tests: "HCM N/N, PKDEF N/N, SMA N/N",
        concours: ["Grand Champion d'Europe","Second chat de France en 2024","Champion du Monde"],
        blabla: "Tempérament équilibré. Uragon est à la fois joueur, curieux, doux et calme. Très proche de son frère Tyson, avec lequel il ne se dispute jamais. Il sera papa pour la seconde fois en mai suite à son mariage avec Udaipur de Mourre-frais qui a eu lieu en mars. Fils du célèbre BigBoss, son pedigree est prestigieux.",
        photos: ["uragon-1.jpeg","uragon-2.jpeg", "uragon-3.jpeg", "uragon-4.jpeg","uragon-5.jpeg"]
    }
];